name: Deploy to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: aevue-com
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: aevue-com
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: |
          gcloud --quiet config set project aevue-com
          gcloud --quiet config set compute/zone us-central1-a

      - name: Deploy to GCP
        run: |
          gcloud --quiet app deploy app.yaml
