name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@latest
        with:
          project_id: aevue-com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/aevue-com/aevue-com:latest
          build-args: |
            HTTP_PORT=3000

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          image: gcr.io/aevue-com/aevue-com:latest
          service: aevue
          region: us-central1
          platform: managed
          allow-unauthenticated: true
          env: |
            FOO=bar
            ZIP=zap
